### ISSUE TITLE
I have a question about Integration with Laravel and google storage

### ISSUE THREAD

**Issue by AhmedHelalAhmed** [ankitpokhrel/tus-php#157]
**Describe the bug**
It's not a bug but a question I have Laravel application and I'm using google storage as storage for my application, I need to upload large files 50 GB or more and searched and found this package I saw this https://github.com/ankitpokhrel/tus-php/wiki/Laravel-&-Lumen-Integration
but it's for Laravel storage is there any way to make it in google storage through Laravel?

**Additional context**

**Comment by georgewritescode** [comment]
@ankitpokhrel I was thinking about this and wondering how this would work with servers which are load balanced and your request could go to any number of servers. With Tus chunking the file together, would this would disrupt the file being created? Perhaps in the future, we could see if it is possible to store the chunks on external storage providers like Google Storage/S3. Because the servers are often located in the same data-centres as storage, there may not be a great effect due to latency.

**Comment by ankitpokhrel** [comment]
@georgewritescode As long as we are using same persistence disk for all servers we should not have any issue. 

I looked into the possibility of storing files directly to s3 sometime back but had to drop the idea since I couldn't manage enough time to work on it. I am open for discussion if anyone wants to help with the external storage implementation. The original [tusd](https://github.com/tus/tusd) implementation already supports direct upload to GCS and S3.
