### ISSUE TITLE
Document v1.0.0 incompatible changes from 0.1.0

### ISSUE THREAD

**Issue by fgm** [ankitpokhrel/tus-php#159]
**Is your feature request related to a problem? Please describe.**
The Vimeo API is currently locked on v0.1.0, and we need to know what they would need to change to allow requiring ^1.0.0 instead of a strict 0.1.0 (see https://github.com/vimeo/vimeo.php/issues/208 ). They had to pin to 0.1.0 to solve an issue with later versions: https://github.com/vimeo/vimeo.php/issues/189

**Describe the solution you'd like**
Either extend the tag description on https://github.com/ankitpokhrel/tus-php/releases/tag/v1.0.0 or add a CHANGELOG.md or a paragraph to https://github.com/ankitpokhrel/tus-php/blob/master/README.md documenting what users need to change to their 0.1.0-based code to be compatible with ^1.0 versions.

**Describe alternatives you've considered**

Hook into the Composer requirements via the pre-dependencies-solving hook to override the dependency on 0.1.0 and, if needed, patch the depending component. Unclean and complex, and it still needs the changes information.

**Additional context**
```bash
$ composer outdated
alchemy/zippy                0.4.3           0.4.9           Zippy, the archive manager companion
ankitpokhrel/tus-php         v0.1.0          v1.0.8          A pure PHP server and client for the tus resumable upload protocol v1.0.0
[...]
$ composer why-not ankitpokhrel/tus-php v1.0.8
vimeo/vimeo-api  3.0.2  requires  ankitpokhrel/tus-php (v0.1.0)
```

**Comment by ankitpokhrel** [comment]
@fgm Previously we assumed that the client was stateless and were constructing the upload url based on the upload key. But later we realized that the client is not completely stateless and it needs to store some information about the upload that it needs to resume (#92 and https://github.com/tus/tus-resumable-upload-protocol/issues/139). v1.0.0 fixes this issue by introducing caching mechanism in the client side [#101](https://github.com/ankitpokhrel/tus-php/pull/101/files#diff-c081bcec36d38ba8db3beffdcc29d3feR340).

In order to upgrade to v1, we need to make sure that the client is either connected to redis (preferred) or is able to create a file based cache during upload.

**Comment by fgm** [comment]
Thanks for this information.

I'm not sure what it will imply for the issues in the Vimeo client I mentioned, though.
