### ISSUE TITLE
Possible to resumes Uploads without Chunks?

### ISSUE THREAD

**Issue by PSchu** [ankitpokhrel/tus-php#202]
I am currently working on a background upload feature on an iOS App and the Server uses this Library.
I Currently have the problem that the uploads are not resumable if I don't upload them in chunks.
My question is now, if this is a constraint of this php implementation?
When I use the test server at https://master.tus.io/files I can resume aborted uploads without using chunks. I Think this test Server uses the GO implementation.

**Comment by ankitpokhrel** [comment]
@PSchu I assume by "I don't upload them in chunks" you mean you are sending whole file in every request. The current design assumes that the server receives data in chunks, so yes this will have issues if the client sends full file in every request.

Is there any specific reason behind sending whole data to server in each request?

**Comment by PSchu** [comment]
Maybe my Question was not detailed enough.

Following Scenario:

We start uploading the Frist time with the whole file.
This upload gets cancelled by something, for example the user turns on Airplane mode on his phone.
Next time we ask the server how much of the file he has with a head request.
The server I am currently working against who uses this library now always returns 0.
The server at https://master.tus.io/files retains the data he got and I can continue where the connection was lost.

If this is a constraint of this library I have a problem doing these uploads in the background.
Because on iOS if I start an UploadTask while the app is in the Background (starting the next chunk) the system will put a delay between these two upload task. This delay will double every time I start a new one.
It only resets to 0 if the user opens the app again.
So I have the make a trade off between chunk size and speed.
If I set the chunk size to high there is a higher risk of loosing progress. If I set the chunk size to low it is really slow because of the delays in between.

Also without the background problem chunked uploads are significantly slower. At least in my tests.


Hope this clears up my question

**Comment by ankitpokhrel** [comment]
> We start uploading the Frist time with the whole file.
This upload gets canceled by something, for example the user turns on Airplane mode on his phone.
Next time we ask the server how much of the file he has with a head request.
The server I am currently working against who uses this library now always returns 0.

This might be because the server is not able to save the state of the upload for some reason. It can be anything like getting out of memory, latency, etc. I would suggest checking server logs to figure out what is actually happening there. 

> If this is a constraint of this library I have a problem doing these uploads in the background.

This is not a constraint to this library. You can spin up the local `tus-php` server and see if the issue is with this library itself. You can use docker to [run it locally](https://github.com/ankitpokhrel/tus-php#setting-up-a-dev-environment-andor-running-examples-locally) and use tunneling like [ngrok](https://ngrok.com/) if you need to access it in iOS. 

In case you find anything, we are happy to help with that.

**Comment by PSchu** [comment]
You are right I tried it with the local docker server in this project and it worked.
Thanks for the help I will try to talk to the backend provider.
