### ISSUE TITLE
Mixed Content Error when using SSL provided by CDN

### ISSUE THREAD

**Issue by amir9480** [ankitpokhrel/tus-php#273]
**Is your feature request related to a problem? Please describe.**
I using a CDN based https/SSL certification.
My server has no SSL and CDN to server communication is without https.
So when uploading a file `location` header is the address of the website But without https then mixed content error happens.

**Describe the solution you'd like**
A method to manually set the root path of the website.
```php
$server = new TusServer(...);

$server
     ->setApiPath('/admin/helpers/uppy/upload')
     ->setUploadDir(...)
     ->setRootPath('https://mywebsite.com');
```

**Additional context**
![image](https://user-images.githubusercontent.com/16279288/84380736-1b38bc00-abfd-11ea-9eb5-c0ce0e972218.png)

**Edit:**
I using this solution for now.
```php
$response = $server->serve();
if (! empty($response->headers->get('location'))) {
    $response->headers->set('location', rtrim(url('/'), '/').'/'.ltrim(array_get(parse_url($response->headers->get('location')), 'path'), '/'));
}
$response->send();
```

**Comment by ankitpokhrel** [comment]
Hi @amir9480 you can use [middleware](https://github.com/ankitpokhrel/tus-php#middleware) to trim and format the URL. You can find some examples of the middleware [here](https://github.com/ankitpokhrel/tus-php/tree/master/src/Middleware).

**Comment by renepardon** [comment]
I have a similar/same error with mixed content. On production everything runs with HTTPS but tus-php doesn't seem to create the location header properly and uses HTTP.

My current hack looks like this:

```php
    public function handleUpload(Request $request)
    {
        /** @var \TusPhp\Tus\Server $tusServer */
        $tusServer = app('tus-server');

        $tusServer->event()->addListener('tus-server.upload.complete', function (TusEvent $event) use ($request) {
            Log::debug('tus-server.upload.complete');
            event(new VideoUploaded($event, $request->user()));
        });

        /** @var \Symfony\Component\HttpFoundation\Response $response */
        $response = $tusServer->serve();

        // TODO (the library should detect https schema automatically and use it!)
        if (! empty($response->headers->get('location')) && config('app.env') === 'production') {
            $response->headers->set('location', str_replace('http:', 'https:', $response->headers->get('location')));
        }

        $response->send();
        exit(0);
    }
```

I check for production environment to force HTTPS. `$request->isSecure()` instead will not do the trick.

**Comment by ankitpokhrel** [comment]
// Ping @samundra

**Comment by ankitpokhrel** [comment]
@amir9480 @renepardon tus-php uses [symfony/http-foundation](https://github.com/symfony/http-foundation/blob/5.x/Request.php) package internally to handle the requests and detecting the protocol is handled dynamically by [getScheme()](https://github.com/symfony/http-foundation/blob/5.x/Request.php#L933-L936) method.

Applications that are behind a reverse proxy needs to forward some HTTP headers such as `X-Forwarded`, `X-Forwarded-For`, `X-Forwarded-Proto` etc so that a server knows details about the client making an HTTP request. I believe these headers are not forwarded to the server in your case and that is causing the issue.

Also see: [Trusted Proxies](https://symfony.com/doc/current/deployment/proxies.html)

**Comment by samundra** [comment]
Hi @amir9480 

I would like to follow up on it. 

Were you able to resolve the problem you had?

**Comment by amir9480** [comment]
@samundra 

I have no control over the headers in the CDN I use. So I still use my old trick:

https://github.com/sanjabteam/sanjab/blob/master/src/Controllers/UppyWidgetController.php#L39

**Comment by amir9480** [comment]
@samundra 

Hi
I have no control over the headers in the CDN I use. So I still use my old trick:

https://github.com/sanjabteam/sanjab/blob/master/src/Controllers/UppyWidgetController.php#L39

**Comment by samundra** [comment]
Hi @amir9480 

Thank your for the feedback.

We'll look into it and hopefully will be able to address it if more users begin to report it. Currently, we have a workaround and thus can be put on hold for now.

**Comment by samundra** [comment]
Hi all,

I did some tests and found that when client is served over https and tus-php server is served over http then we get mixed content error.

Please see test result below:

## Testing methods

| Test case | Client | Server | Behind <br/>Reverse Proxy | Reproduced<br/> Mixed Content |
| --------- | ------ | ------ | -------------------- | ------------------------ |
| Case 1    | https  | https  | ❌                   | ❌                       |
| Case 2    | http   | https  | ❌                   | ❌                       |
| Case 3    | https  | http   | ❌                   | ✅                      |
| Case 4    | https  | https  | ✅                  | TODO                     |


### Case 1: both client and server with https (no proxy in-between)

Server URL configured on client side:
```
$client = new \TusPhp\Tus\Client('https://e4063466d30b.ngrok.io');
```

**Result:** ❌ (Couldn't reproduce the issue)

### Case 2: Client http and server with https (no proxy in-between)

Server URL configured on client side:
```
$client = new \TusPhp\Tus\Client('https://e4063466d30b.ngrok.io');
```

**Result:** ❌ (Couldn't reproduce the issue)

### Case 3: Client https and server with http (using uppy tus client)

Server URL configured on client side:
```
$client = new \TusPhp\Tus\Client('http://e4063466d30b.ngrok.io');
```

Uppy Tus-Client using hard-coded path to `http://tusphp.local/files/`

```
 const uppy = Uppy.Core({debug: true, autoProceed: false})
    .use(Uppy.Dashboard, {target: '#uppyUploader', inline: true})
    .use(Uppy.Tus, {endpoint: 'http://tusphp.local/files/'})
    .run()
```

**Result:** ✅  Got Mixed content issue. This is expected behavior and is not a bug. This could mean that there is some configuration issue while setting up tus-php server and client.


### Case 4: Client https and Server hosted behind reverse proxy
[todo]

### Assumptions

Based on test case 1, 2 and 3. So far it looks like Case 4 could likely be the issue with most people. If the tus-php server is hosted behind reverse proxy then tus-php server maynot be receiving the headers correctly. This can happen if proxy server is not configured to pass headers to downstream servers

**Comment by renepardon** [comment]
.unstale

**Comment by renepardon** [comment]
No final solution so far?

**Comment by stloc** [comment]
for me it is solved with : 

```
framework:
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-host' ]
```
