### ISSUE TITLE
Make forbidden filenames configurable

### ISSUE THREAD

**Issue by eFrane** [ankitpokhrel/tus-php#333]
**Is your feature request related to a problem? Please describe.**

I just spent the better part of two hours trying to figure out why my uploading code was suddenly broken for a single file and working fine for every other test file until I finally debugged myself to `src/Request.php:232`. While I understand the possible security implications of allowing all filenames, I would like to open up the discussion on the filter list.

**Describe the solution you'd like**

Ideally, this should be user-configurable. Not allowing any navigational path elements (`..`, `/`, etc.) should likely be a default setting. It may even be non-negotiable, although, who knows. I'm generally a strong defender of not restricting users if the users are developers. But, to my knowledge, there's at least all Linuxes and macOS which have no issue at all with `#`, `&`, and the likes. Maybe there's some middle ground here. 

Side note:

Wouldn't it be cleaner to extract the file / meta validation into a separate class? That may also make things less understandable. Hm. 🤔 

**Describe alternatives you've considered**

As I'm integrating this into a Symfony application I could probably just overwrite the Request class but that seems awfully over-engineered and the wrong approach to the problem.

Thanks for this time-saving library and happy holidays! 🎄 
Oh, and to mention it, I'm absolutely up for implementing a pull request once a possible solution has been discussed.

**Comment by ankitpokhrel** [comment]
Hi @eFrane, sorry for the delayed response and hope you had a wonderful holiday.

I wouldn't mind making this configurable given that:
- The default behavior restricts possibly illegal characters as we have at the moment.
- Navigational elements must not be configurable (unless someone comes up with a valid reason to do so).

PRs are welcome :)

> Wouldn't it be cleaner to extract the file / meta validation into a separate class?

There is always a cleaner way of doing things, and sometimes it is just a personal preference 😉. The `Request` class not doing much at the moment, but in case it starts getting bloated we can think of design alterations.

**Comment by klammbueddel** [comment]
> I just spent the better part of two hours trying to figure out why my uploading code was suddenly broken
Same for me here. My client side validation allows `'`, `&` and `#` since our targeted file systems support these characters. I see no reason why these characters should not be allowed. Sure, they must be escaped appropriate when being used in URLs but you have to deal with this anyway. Making it configurable would be nice, but IMHO the default is a bit too strict here.

Debugging it would have been faster if the reason for the HTTP 400 would have been put to the payload of the response. Distinguishing "Filename is empty" and "Filename is invalid" would be nice. Took me a while until I saw that the issue is caused by illegal filenames and not by empty ones.

**Comment by eFrane** [comment]
s**t, this fell under my radar. I started implementing a PR for this. I'll try to find time to make it push-able.
