### ISSUE TITLE
Unable to create resource

### ISSUE THREAD

**Issue by greatsami** [ankitpokhrel/tus-php#338]
Hello, 

I'm trying for 2 days with this issue.

I'm working on:
Windows 10
Laravel 8 
Redis

I followed Laravel & Lumen Integration, also I implemented Basic example.

My problem in Upload function in FileException

the response from verify function:

```
{"status":"new","bytes_uploaded":0,"upload_key":"tus_file_6023bf72e3b8f"}
```

the response from upload function:

```
{"status":"error","bytes_uploaded":-1,"upload_key":"","error":"Unable to create resource."}
```

when I print the value of src/Tus/Client.php line 488

```
dd(HttpResponse::HTTP_CREATED , $statusCode)
```

HttpResponse::HTTP_CREATED = 201
$statusCode = 404

My routes in web.php:  

```
Route::get('create', [\App\Http\Controllers\UploadController::class, 'create'])->name('upload.create');
Route::post('verify', [\App\Http\Controllers\UploadController::class, 'verify'])->name('upload.verify');
Route::post('upload', [\App\Http\Controllers\UploadController::class, 'upload'])->name('upload.upload');

Route::any('/tus/{any?}', function () {
    return app('tus-server')->serve();
})->where('any', '.*');
```

What I can solve this?

**Comment by kailasb** [comment]
> Hello,
> 
> I'm trying for 2 days with this issue.
> 
> I'm working on:
> Windows 10
> Laravel 8
> Redis
> 
> I followed Laravel & Lumen Integration, also I implemented Basic example.
> 
> My problem in Upload function in FileException
> 
> the response from verify function:
> 
> ```
> {"status":"new","bytes_uploaded":0,"upload_key":"tus_file_6023bf72e3b8f"}
> ```
> 
> the response from upload function:
> 
> ```
> {"status":"error","bytes_uploaded":-1,"upload_key":"","error":"Unable to create resource."}
> ```
> 
> when I print the value of src/Tus/Client.php line 488
> 
> ```
> dd(HttpResponse::HTTP_CREATED , $statusCode)
> ```
> 
> HttpResponse::HTTP_CREATED = 201
> $statusCode = 404
> 
> My routes in web.php:
> 
> ```
> Route::get('create', [\App\Http\Controllers\UploadController::class, 'create'])->name('upload.create');
> Route::post('verify', [\App\Http\Controllers\UploadController::class, 'verify'])->name('upload.verify');
> Route::post('upload', [\App\Http\Controllers\UploadController::class, 'upload'])->name('upload.upload');
> 
> Route::any('/tus/{any?}', function () {
>     return app('tus-server')->serve();
> })->where('any', '.*');
> ```
> 
> What I can solve this?

getting same issue but it works locally.
can any one guide how to resolved this issue?

**Comment by ankitpokhrel** [comment]
> $statusCode = 404

This usually means the route you are sending request to doesn't exist, hence 404. Please make sure that the tus routes are working and the client is sending request to the proper routes.

**Comment by kailasb** [comment]
I'm facing the issue while upload the video. I'm using paid version of vimeo.
it's working fine locally but it create the URL with **https://asia-files.tus.vimeo.com/files/vimeo-prod-src-tus-asia/3db9d46ef63cdfb01112798c352b05de**

but when I upload the video from server it generating URL like **https://europe-files.tus.vimeo.com/files/vimeo-prod-src-tus-eu/62566c38373b68318218e1f2b8239eb5** this and getting error "Unable to create resource"

I've found only one difference is the region name: **"asia"** & **"europe"**

@ankitpokhrel do you have any idea about it?

**Comment by ankitpokhrel** [comment]
@kailasb It should not be a problem as long as you operate in the same region. Meaning, if you upload a file in region `europe` and try to access the file from the same region `europe` it should be fine.

I believe the issue you are facing is probably due to some misconfiguration in your server. Additional information will be helpful to debug the issue. You can check your server error logs to look for the clues.

**Comment by kailasb** [comment]
Below is the code I'm using. Application build in laravel
```
                    $uploadedFile = $request->file('video_url');
                    $vimeo = new \Vimeo\Vimeo(env("VIMEO_KEY"), env("VIMEO_SECRET"), env("VIMEO_ACCESSTOKEN"));
                    $private = array("embed" => "public", "view" => "unlisted", "download" => false);
                    $upload_link = array(
                        "approach" => "pull",
                        "size" => "{size}",
                        "link" => "{url}"
                    );
                    $file_name = $uploadedFile->getRealPath();

                    try {
                        $uri = $vimeo->upload($uploadedFile, array(
                            "name" => "Course featured video:" . Auth::user()->id . " " . date("d-m-Y"),
                            "description" => $request->title,
                            "privacy" => $private,
                            "upload" => $upload_link
                        ));
                    } catch (VimeoUploadException $e) {
                        return response()->json(['status' => '500', 'data' => $e->getMessage()]);
                    } catch (VimeoRequestException $e) {
                        return response()->json(['status' => '500', 'data' => $e->getMessage()]);
                    }
```
can you tell me what wrong in the setting?

**Comment by samundra** [comment]
Hi @kailasb 

Since you are using `pull` approach, could you please ensure that video that you are trying to upload is reachable publicly? It could possibly be that video is unreachable or server where it is hosted is blocking direct request to it (hotlinking not allowed etc.) What response do you get when you do a basic `curl -I video_url`. Do you get the 200 or some other http status code?

Besides, have you already followed the instruction given in https://developer.vimeo.com/api/upload/videos
![Screen Shot 2021-03-19 at 00 56 40](https://user-images.githubusercontent.com/760855/111674259-65b32d00-884e-11eb-917b-fdbbe829dcf2.png)

If so, also please ensure that video which you are trying to upload is directly accessible over public url as state on vimeo integration page, https://developer.vimeo.com/api/upload/videos#pull-approach

![Screen Shot 2021-03-19 at 00 57 01](https://user-images.githubusercontent.com/760855/111674368-824f6500-884e-11eb-8aec-820743364ae4.png)

Once we are sure that video is publicly accessible and can be reached by Vimeo api then we can further debug regarding why Tus-php is unable to create resource.

**Comment by kailasb** [comment]
This is error I'm getting
![image](https://user-images.githubusercontent.com/12524587/111739765-9bd1ca80-88a9-11eb-8d38-4f03ac88ac79.png)

**Comment by kailasb** [comment]
can you guide why this issue I'm getting?

**Comment by kailasb** [comment]
I've checked in vimeo plugin it's set internally approach set to "tus".
```
[body] => Array
        (
            [uri] => /videos/528701157
            [upload] => Array
                (
                    [status] => in_progress
                    [upload_link] => https://europe-files.tus.vimeo.com/files/vimeo-prod-src-tus-eu/c236158a3c3bb144979b7964fbbadca7
                    [form] => 
                    [complete_uri] => 
                    [approach] => tus
                    [size] => 1053651
                    [redirect_url] => 
                    [link] => 
                )

        )
```
after it's calling your  plugin upload function and getting "Unable to create resource" error.
can you guide more on this?

**Comment by daslicht** [comment]
I am getting teh samne error with teh basic example of this project / vanilla php
