### ISSUE TITLE
Client should check Upload-Expires header during upload

### ISSUE THREAD

**Issue by ankitpokhrel** [ankitpokhrel/tus-php#97]
The Client SHOULD use Upload-Expires header to determine if an upload is still valid before attempting to resume the upload.

https://tus.io/protocols/resumable-upload.html#upload-expires

**Comment by AurelienMendes** [comment]
Hello Ankit,
I'm so glad because you helped me to integrate TUS protocol in my Laravel application !!!
However, there is some strange behaviors with Upload-Expires, since I got randomly 410 Gone error on multiple file upload with Uppy Client and your Server.
For example, the same test done twice, which consists in trying to upload at same time 4 images (around 100Ko each) gives me
First time 
[image](https://user-images.githubusercontent.com/44461190/48354622-75c10d80-e692-11e8-8637-79c4a949522a.png)
Second time
![image](https://user-images.githubusercontent.com/44461190/48354774-d05a6980-e692-11e8-9bdd-52277a39fadd.png)

Not seen on these sreenshots, each time I got a 410 error, the associated tus request has a Upload-Expires empty/null
I'm trying to understand, but I don't find the reason why even if everything seems to incriminate Upload-Expires ... and that's really problematic.

Do you have an idea ?

PS : I use Filestore for cache, Laravel 5.7 with everything uptodate and work locally.

**Comment by ankitpokhrel** [comment]
> I use Filestore for cache, Laravel 5.7 with everything uptodate and work locally.

> the problem comes from parallel upload clearly ... when I set the option "limit: 1" in the Uppy.TUS object

@AurelienMendes From these statements I assume that this might be happening:
- You are using FileStore for cache.
- You initiate multiple parallel uploads using uppy.
- Uppy tries to write metadata in file parallelly.
- As FileStore is simple cache implementation and doesn't count for [Readers-writers problem](https://en.wikipedia.org/wiki/Readers%E2%80%93writers_problem), one key can be overridden by another if multiple requests come at the same time. Thus, causing 410 gone error in another upload.

You can switch to redis store and it should work fine.
